"""nucleo monetario: usuario, convite, transacao

Revision ID: 18b2059732ae
Revises: 
Create Date: 2026-08-31 21:00:22.752643

"""
from alembic import op
import sqlalchemy as sa

# O tipo monetário é do projeto; sem este import a migração não roda.
import vavacoin.dinheiro


# revision identifiers, used by Alembic.
revision = '18b2059732ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('eh_banco_central', sa.Boolean(), nullable=False),
    sa.Column('saldo', vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('NOT eh_banco_central OR senha_hash IS NULL', name='ck_banco_central_sem_senha'),
    sa.CheckConstraint('saldo >= 0', name='ck_usuario_saldo_nao_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_nome_usuario'), ['nome_usuario'], unique=True)

    op.create_table('convite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('destinatario', sa.String(length=80), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('resgatado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('convite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convite_codigo'), ['codigo'], unique=True)

    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('valor', vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('saldo_origem_depois', vavacoin.dinheiro.Dinheiro(), nullable=True),
    sa.Column('saldo_destino_depois', vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(origem_id IS NOT NULL) OR tipo = 'genese'", name='ck_transacao_sem_origem_so_na_genese'),
    sa.CheckConstraint('origem_id IS NULL OR origem_id <> destino_id', name='ck_transacao_origem_diferente_destino'),
    sa.CheckConstraint('valor > 0', name='ck_transacao_valor_positivo'),
    sa.ForeignKeyConstraint(['destino_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['origem_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacao_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_destino_id'), ['destino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_origem_id'), ['origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacao_tipo'))
        batch_op.drop_index(batch_op.f('ix_transacao_origem_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_destino_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_criado_em'))

    op.drop_table('transacao')
    with op.batch_alter_table('convite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convite_codigo'))

    op.drop_table('convite')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nome_usuario'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
