"""banco central autentica, ator no ledger, diario do painel

O Banco Central passa a entrar pelo site, então cai o CHECK que o proibia de
ter senha. Isso recria a tabela `usuario` — a que guarda os 5.000 —, porque
o SQLite não tem DROP CONSTRAINT. **Faça backup do .sqlite3 antes de rodar** e
`flask auditoria` depois.

O `copy_from` abaixo não é preciosismo: o SQLAlchemy não reflete CHECK do
SQLite, então um batch_alter_table sem ele recriaria a tabela sem CHECK
nenhum — levando junto o `saldo >= 0`, que é a última rede contra saldo
negativo. A definição explícita mantém o que deve ficar e tira só o que deve
sair.

Revision ID: 353a30f6e6f5
Revises: 18b2059732ae
Create Date: 2026-08-31 22:21:14.670282

"""
from alembic import op
import sqlalchemy as sa
import vavacoin.dinheiro


# revision identifiers, used by Alembic.
revision = '353a30f6e6f5'
down_revision = '18b2059732ae'
branch_labels = None
depends_on = None


USUARIO_ANTES = sa.Table(
    "usuario",
    sa.MetaData(),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("nome_usuario", sa.String(length=50), nullable=False),
    sa.Column("nome_exibicao", sa.String(length=80), nullable=False),
    sa.Column("senha_hash", sa.String(length=128), nullable=True),
    sa.Column("eh_banco_central", sa.Boolean(), nullable=False),
    sa.Column("saldo", vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("saldo >= 0", name="ck_usuario_saldo_nao_negativo"),
    sa.CheckConstraint(
        "NOT eh_banco_central OR senha_hash IS NULL",
        name="ck_banco_central_sem_senha",
    ),
    sa.PrimaryKeyConstraint("id"),
)

USUARIO_DEPOIS = sa.Table(
    "usuario",
    sa.MetaData(),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("nome_usuario", sa.String(length=50), nullable=False),
    sa.Column("nome_exibicao", sa.String(length=80), nullable=False),
    sa.Column("senha_hash", sa.String(length=128), nullable=True),
    sa.Column("eh_banco_central", sa.Boolean(), nullable=False),
    sa.Column("saldo", vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("saldo >= 0", name="ck_usuario_saldo_nao_negativo"),
    sa.PrimaryKeyConstraint("id"),
)


def upgrade():
    # O Banco Central pode ter senha a partir daqui. O `saldo >= 0` fica.
    with op.batch_alter_table(
        "usuario", schema=None, copy_from=USUARIO_ANTES, recreate="always"
    ) as batch_op:
        batch_op.drop_constraint("ck_banco_central_sem_senha", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_administrativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ator_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=40), nullable=False),
    sa.Column('alvo', sa.String(length=80), nullable=True),
    sa.Column('detalhe', sa.String(length=300), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_administrativo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_administrativo_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_administrativo_ator_id'), ['ator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_administrativo_criado_em'), ['criado_em'], unique=False)

    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ator_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transacao_ator_id'), ['ator_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_transacao_ator_id_usuario', 'usuario', ['ator_id'], ['id']
        )
        batch_op.drop_constraint(batch_op.f('ck_transacao_sem_origem_so_na_genese'), type_='check')
        batch_op.create_check_constraint('ck_transacao_sem_origem_so_emite', "(origem_id IS NOT NULL) OR tipo IN ('genese', 'emissao')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_constraint('ck_transacao_sem_origem_so_emite', type_='check')
        batch_op.create_check_constraint(batch_op.f('ck_transacao_sem_origem_so_na_genese'), "(origem_id IS NOT NULL) OR tipo = 'genese'")
        batch_op.drop_constraint('fk_transacao_ator_id_usuario', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transacao_ator_id'))
        batch_op.drop_column('ator_id')

    # Volta a proibir senha no Banco Central. Se ele já tiver uma, o CHECK
    # falha na recriação — de propósito: apagar a senha por baixo seria
    # decidir sozinho que o god mode acabou.
    with op.batch_alter_table(
        "usuario", schema=None, copy_from=USUARIO_DEPOIS, recreate="always"
    ) as batch_op:
        batch_op.create_check_constraint(
            "ck_banco_central_sem_senha",
            "NOT eh_banco_central OR senha_hash IS NULL",
        )

    with op.batch_alter_table('registro_administrativo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_administrativo_criado_em'))
        batch_op.drop_index(batch_op.f('ix_registro_administrativo_ator_id'))
        batch_op.drop_index(batch_op.f('ix_registro_administrativo_acao'))

    op.drop_table('registro_administrativo')
    # ### end Alembic commands ###
