"""caladinho: conta da casa, rodadas de mines e configuracao

Acrescenta a conta da casa (uma coluna em `usuario`), a tabela das rodadas e a
de configuração — o interruptor do caixa visível.

O índice `uq_uma_rodada_ativa_por_jogador` é **parcial**: único só onde
`estado = 'ativa'`. É o que impede duas rodadas ativas do mesmo jogador mesmo
em corrida entre processos, sem impedir o histórico de ter várias encerradas.

Aditiva: nenhuma tabela é recriada, então os índices de `usuario` ficam onde
estão.

Revision ID: 3ad5db7b3668
Revises: 5e2a8edc70ea
Create Date: 2026-09-01 13:02:14.671778

"""
from alembic import op
import sqlalchemy as sa
import vavacoin.dinheiro


# revision identifiers, used by Alembic.
revision = '3ad5db7b3668'
down_revision = '5e2a8edc70ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracao_chave'), ['chave'], unique=True)

    op.create_table('rodada_mines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('aposta', vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column('minas_escolhidas', sa.Integer(), nullable=False),
    sa.Column('minas', sa.String(length=120), nullable=False),
    sa.Column('reveladas', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('multiplicador', vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column('premio', vavacoin.dinheiro.Dinheiro(), nullable=False),
    sa.Column('transacao_aposta_id', sa.Integer(), nullable=True),
    sa.Column('transacao_premio_id', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('ativa', 'estourada', 'retirada')", name='ck_rodada_estado'),
    sa.CheckConstraint('aposta > 0', name='ck_rodada_aposta_positiva'),
    sa.CheckConstraint('minas_escolhidas >= 1 AND minas_escolhidas <= 24', name='ck_rodada_minas'),
    sa.ForeignKeyConstraint(['jogador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['transacao_aposta_id'], ['transacao.id'], ),
    sa.ForeignKeyConstraint(['transacao_premio_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rodada_mines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rodada_mines_criada_em'), ['criada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_rodada_mines_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_rodada_mines_jogador_id'), ['jogador_id'], unique=False)
        batch_op.create_index('uq_uma_rodada_ativa_por_jogador', ['jogador_id'], unique=True, sqlite_where=sa.text("estado = 'ativa'"), postgresql_where=sa.text("estado = 'ativa'"))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        # server_default é obrigatório: a coluna é NOT NULL e a tabela já tem
        # gente dentro. Sem ele a migração morre no primeiro banco real.
        batch_op.add_column(
            sa.Column(
                'eh_cassino', sa.Boolean(), nullable=False, server_default=sa.text('0')
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('eh_cassino')

    with op.batch_alter_table('rodada_mines', schema=None) as batch_op:
        batch_op.drop_index('uq_uma_rodada_ativa_por_jogador', sqlite_where=sa.text("estado = 'ativa'"), postgresql_where=sa.text("estado = 'ativa'"))
        batch_op.drop_index(batch_op.f('ix_rodada_mines_jogador_id'))
        batch_op.drop_index(batch_op.f('ix_rodada_mines_estado'))
        batch_op.drop_index(batch_op.f('ix_rodada_mines_criada_em'))

    op.drop_table('rodada_mines')
    with op.batch_alter_table('configuracao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracao_chave'))

    op.drop_table('configuracao')
    # ### end Alembic commands ###
