"""mines: registra a casa que estourou

Revision ID: 7289a82f96d2
Revises: 3ad5db7b3668
Create Date: 2026-09-01 13:30:41.635696

"""
from alembic import op
import sqlalchemy as sa
import vavacoin.dinheiro


# revision identifiers, used by Alembic.
revision = '7289a82f96d2'
down_revision = '3ad5db7b3668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rodada_mines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_estourada', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rodada_mines', schema=None) as batch_op:
        batch_op.drop_column('casa_estourada')

    # ### end Alembic commands ###
